//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTB
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventStartsDate { get; set; }
        public Nullable<System.DateTime> EventEndsDate { get; set; }
        public string EventLocation { get; set; }
    }
}
